# Generated by Django 4.2.3 on 2023-08-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoupSwap_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mble',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gdr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_type',
        ),
    ]
