# Generated by Django 4.2.3 on 2023-08-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoupSwap_App', '0002_rename_mble_user_mobile_remove_user_eid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='demandedamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
