# Generated by Django 4.2.3 on 2023-08-13 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoupSwap_App', '0004_alter_coupon_demandedamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoupSwap_App.coupon')),
                ('requestedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
