# Generated by Django 4.2.3 on 2023-08-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoupSwap_App', '0005_couponrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='requestedby',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usedby',
            field=models.IntegerField(null=True),
        ),
    ]
