# Generated by Django 4.2.3 on 2023-08-26 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoupSwap_App', '0007_delete_couponrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('Coupon Used', 'Coupon Used')], default='Deposit', max_length=15, verbose_name='Type of transaction')),
                ('coupondet', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoupSwap_App.coupon')),
                ('creditto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Credit', to=settings.AUTH_USER_MODEL)),
                ('debitfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
